name: Publicação Docker Imagens

on:
  push:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Enviar Imagem Docker ao Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  repo
        uses: actions/checkout@v4
      
      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: "dyegodev30"
          password: "dckr_pat_QZf6qc6slubGle9VbCHmdQFU7QU"
      
      - name: Extração de dados do Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: "dyegodev30/testepush"
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "dyegodev30/gabu:teste_push_dockerhub"
          #####################################
